# Generated by Django 2.2.7 on 2020-10-24 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_test',
        ),
    ]
